# Each user to be their own dictionary with the same variables

[alice]
host = "https://plex.example.com"
token = "abcd"
musicLibrary = 1
playlists = [123, 456, 789]

[bob]
host = "https://plex.example.ca"
token = "efgh"
musicLibrary = 1
playlists = [987, 654, 321]